import React, { Component, Fragment } from 'react';
import { API, Auth, graphqlOperation } from 'aws-amplify';
import validUrl from 'valid-url';

// Take autogenerated mutation.
import { createPost } from '../graphql/mutations';

class Share extends Component {
  state = {
    disabled: true,
    feedback: '',
    notes: '',
    tags: '',
    url: '',
    author: '',
  };

  async componentDidMount() {
    try {
      // If federated with cognito: userData.attributes.name
      // If directly from user pool: data.name
      const userData = await Auth.currentAuthenticatedUser();

      const author =
        userData && userData.attributes && userData.attributes.name
          ? userData.attributes.name
          : userData.name;

      this.setState({ author });
    } catch (error) {
      const feedback =
        'There was an issue while fetching information about current user';

      this.setState({ feedback });
      console.error(feedback, error);
    }
  }

  handleChange = e => {
    const target = e.target;
    const name = target.name;
    const value = target.type === 'checkbox' ? target.checked : target.value;

    // The most naive validation!
    if (validUrl.isUri(this.state.url)) {
      this.setState({ disabled: false });
    } else {
      this.setState({ disabled: true });
    }

    this.setState({
      [name]: value,
    });
  };

  handleSubmit = e => {
    e.preventDefault();

    const { url, notes, tags, author } = this.state;
    const date = new Date().toISOString();
    const tagsList = tags
      ? tags
          .split(',')
          .map(tag => tag.trim())
          .map(tag => tag.toLowerCase())
          .filter(tag => tag)
      : [];

    const newPost = { author, url, notes, date, tags: tagsList };

    API.graphql(graphqlOperation(createPost, { input: newPost }))
      .then(result => {
        const feedback = 'New post has been created successfully!';
        this.setState({ feedback });
        console.log(JSON.stringify(result));
      })
      .catch(e => {
        const feedback = 'Error while trying to create a new shared post!';
        this.setState({ feedback: `${feedback}\n${JSON.stringify(e)}` });
        console.error(feedback, e);
      });
  };

  render() {
    const { disabled, feedback } = this.state;

    return (
      <Fragment>
        <p>Sharing is caring!</p>
        {feedback ? <p>{feedback}</p> : ''}
        <form onSubmit={this.handleSubmit}>
          <label htmlFor="url">
            URL
            <input
              onChange={this.handleChange}
              name="url"
              type="text"
              id="url"
            />
          </label>
          <br />
          <label htmlFor="tags">
            Tags, comma separated
            <input
              onChange={this.handleChange}
              name="tags"
              type="text"
              id="tags"
            />
          </label>
          <br />
          <label htmlFor="notes">
            Notes
            <textarea onChange={this.handleChange} name="notes" id="notes" />
          </label>
          <br />
          <input disabled={disabled ? true : false} type="submit" value="Go!" />
        </form>
      </Fragment>
    );
  }
}

export default Share;
